### ISSUE TITLE
IDE scrolling doesn't work in FF

### ISSUE THREAD

**Issue by jakabakos** [avatao-content/frontend-tutorial-framework#51]
Open an arbitrary tutorial on the new platform that has IDE. 
Eg.: Integer Overflow in Java
When the cursor is over the are of the IDE and you scrolling with the mouse, nothing happens.
It's an issue only under Firefox. Tested with version 70.0.1.

**Comment by therealkrispet** [comment]
Fixed in `chausie-20191108`
